### ISSUE TITLE
Uncaught TypeError: Cannot read property 'alwaysOn' of undefined

### ISSUE THREAD

**Issue by grzbielok** [OleMchls/atom-wordcount#92]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.24.0 x64
**Electron**: 1.6.16
**OS**: Mac OS X 10.13.3
**Thrown From**: [atom-wordcount-master](https://github.com/nesQuick/atom-wordcount) package 2.10.4

### Stack Trace

Uncaught TypeError: Cannot read property 'alwaysOn' of undefined

```
At /Users/dominicgrzbielok/.atom/packages/atom-wordcount-master/lib/main.coffee:117

TypeError: Cannot read property 'alwaysOn' of undefined
    at Object.show_or_hide_for_item (/packages/atom-wordcount-master/lib/main.coffee:117:6)
    at /packages/atom-wordcount-master/lib/main.coffee:100:8
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at Workspace.didChangeActivePaneItemOnPaneContainer (/Applications/Atom.app/Contents/Resources/app/src/workspace.js:492:28)
    at WorkspaceCenter.paneContainer.onDidChangeActivePaneItem (/Applications/Atom.app/Contents/Resources/app/src/workspace-center.js:17:20)
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at PaneContainer.didChangeActiveItemOnPane (/Applications/Atom.app/Contents/Resources/app/src/pane-container.js:284:26)
    at Pane.setActiveItem (/Applications/Atom.app/Contents/Resources/app/src/pane.js:436:48)
    at Pane.activateItem (/Applications/Atom.app/Contents/Resources/app/src/pane.js:575:18)
    at TabBarView.module.exports.TabBarView.onClick (/Applications/Atom.app/Contents/Resources/app/node_modules/tabs/lib/tab-bar-view.js:721:25)
```

### Commands

```
 14x -1:22.7.0 core:backspace (input.hidden-input)
     -1:08.4.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.30.9 
wordcount 2.10.4 
autocomplete-wordpress-hooks 0.2.3 
color-picker 2.2.5 
emmet 2.4.3 
highlight-selected 0.13.1 
jekyll 2.1.0 
language-confluence-wiki 0.2.0 
language-liquid 0.6.0 
language-mjml 1.10.0 
markdown-scroll-sync 2.1.2 
markdown-themeable-pdf 1.2.0 
markdown-writer 2.7.3 
minimap 4.29.7 
pdf-view 0.65.0 
project-manager 3.3.5 
split-diff 1.5.2 
tool-bar 1.1.6 
tool-bar-markdown-writer 0.3.1 
```

**Comment by OleMchls** [comment]
Please reopen with steps to reproduce
