### ISSUE TITLE
Opening a large file throughs an uncaught error that the buffer's content is too large to fit in a string

### ISSUE THREAD

**Issue by keelanfh** [OleMchls/atom-wordcount#93]
1. Attempt to open large file.

**Atom**: 1.24.0 x64
**Electron**: 1.6.16
**OS**: Mac OS X 10.13.3
**Thrown From**: [wordcount](https://github.com/nesQuick/atom-wordcount) package 2.10.4

### Stack Trace

Uncaught Error: This buffer's content is too large to fit into a string.

Consider using APIs like `getTextInRange` to access the data you need.

```
At /Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:537

Error: This buffer's content is too large to fit into a string.

Consider using APIs like `getTextInRange` to access the data you need.
    at TextBuffer.module.exports.TextBuffer.getText (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:537:94)
    at TextEditor.getText (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:1171:41)
    at WordcountView.module.exports.WordcountView.getTexts (/packages/wordcount/lib/wordcount-view.coffee:56:25)
    at WordcountView.getTexts (/packages/wordcount/lib/wordcount-view.coffee:2:1)
    at WordcountView.module.exports.WordcountView.update_count (/packages/wordcount/lib/wordcount-view.coffee:17:14)
    at /packages/wordcount/lib/main.coffee:88:24
    at debounced (/packages/wordcount/node_modules/lodash/index.js:7737:27)
    at /packages/wordcount/lib/main.coffee:102:7
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at Workspace.didChangeActivePaneItemOnPaneContainer (/Applications/Atom.app/Contents/Resources/app/src/workspace.js:492:28)
    at WorkspaceCenter.paneContainer.onDidChangeActivePaneItem (/Applications/Atom.app/Contents/Resources/app/src/workspace-center.js:17:20)
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at PaneContainer.didChangeActiveItemOnPane (/Applications/Atom.app/Contents/Resources/app/src/pane-container.js:284:26)
    at Pane.setActiveItem (/Applications/Atom.app/Contents/Resources/app/src/pane.js:436:48)
    at Pane.activateNextRecentlyUsedItem (/Applications/Atom.app/Contents/Resources/app/src/pane.js:484:18)
    at HTMLElement.pane:show-next-recently-used-item (/Applications/Atom.app/Contents/Resources/app/src/register-default-commands.js:15:54)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:388:36)
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:621:22)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:412:28)
    at WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:108:40)
```

### Commands

```
     -2:04.6.0 snippets:next-tab-stop (input.hidden-input)
     -2:04.6.0 snippets:expand (input.hidden-input)
     -2:04.6.0 editor:indent (input.hidden-input)
     -2:04.5.0 snippets:next-tab-stop (input.hidden-input)
     -2:04.5.0 snippets:expand (input.hidden-input)
     -2:04.5.0 editor:indent (input.hidden-input)
  2x -2:03.4.0 core:backspace (input.hidden-input)
     -0:16.8.0 editor:newline (input.hidden-input)
     -0:12.5.0 pane:show-next-recently-used-item (input.hidden-input)
     -0:11.4.0 pane:move-active-item-to-top-of-stack (input.hidden-input)
```

### Non-Core Packages

```
advanced-open-file 0.16.7 
autocomplete-python 1.10.5 
Hydrogen undefined 
kite 0.75.0 
language-haskell 1.17.3 
language-latex 1.1.1 
python-tools 0.6.9 
script 3.17.3 
svg-preview 0.12.1 
tablr 1.8.3 
teletype 0.9.0 
ult-terminal 0.2.2 
wordcount 2.10.4 
```

**Comment by keelanfh** [comment]
Just realised this is a duplicate of #87
